import { type Config, transform } from "@bare-ts/tools";
import * as fs from "fs/promises";
import * as path from "path";

export interface CompileOptions {
	schemaPath: string;
	outputPath: string;
	config?: Partial<Config>;
	runtimeImportPath?: string;
}

export interface CompileDirectoryOptions {
	inputDir: string;
	outputDir: string;
	config?: Partial<Config>;
	runtimeImportPath?: string;
}

export async function compileSchema(options: CompileOptions): Promise<void> {
	const { schemaPath, outputPath, config = {}, runtimeImportPath } = options;

	let schema = await fs.readFile(schemaPath, "utf-8");

	// Simple preprocessing: strip lines starting with '//' comments which the parser may not accept
	schema = schema
		.split(/\r?\n/)
		.filter((line) => !line.trimStart().startsWith("//"))
		.join("\n");

	// Normalize map<A, B> -> map<A><B> for parser compatibility
	schema = schema.replace(/map<([^,>]+),\s*([^>]+)>/g, "map<$1><$2>");

	// Convert snake_case field names to camelCase to satisfy semantic checks
	const toCamel = (name: string) =>
		name.replace(/_([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase());

	// Replace struct field declarations like `  created_at: ...` -> `  createdAt: ...`
	schema = schema.replace(
		/^(\s*)([a-z][a-z0-9_]*)(\s*:\s*)/gim,
		(_m, p1: string, p2: string, p3: string) => {
			return `${p1}${toCamel(p2)}${p3}`;
		},
	);
	const outputDir = path.dirname(outputPath);

	await fs.mkdir(outputDir, { recursive: true });

	const defaultConfig: Partial<Config> = {
		pedantic: true,
		generator: "ts",
		...config,
	};

	let result = transform(schema, defaultConfig);

	result = postProcessGeneratedTs(result, {
		schemaVersion: parseSchemaVersion(schemaPath),
		runtimeImportPath,
	});

	await fs.writeFile(outputPath, result);
}

export async function compileSchemaDirectory(
	options: CompileDirectoryOptions,
): Promise<void> {
	const { inputDir, outputDir, config = {}, runtimeImportPath } = options;
	const resolvedInput = path.resolve(inputDir);
	const resolvedOutput = path.resolve(outputDir);

	await fs.mkdir(resolvedOutput, { recursive: true });

	const entries = await fs.readdir(resolvedInput, { withFileTypes: true });
	const bareFiles = entries
		.filter((entry) => entry.isFile() && entry.name.endsWith(".bare"))
		.map((entry) => entry.name)
		.sort();

	if (bareFiles.length === 0) {
		throw new Error(`No .bare files found in ${resolvedInput}`);
	}

	let latestVersion: number | null = null;

	for (const file of bareFiles) {
		const schemaPath = path.join(resolvedInput, file);
		const base = file.replace(/\.bare$/, "");
		const outputPath = path.join(resolvedOutput, `${base}.ts`);

		await compileSchema({
			schemaPath,
			outputPath,
			config: {
				pedantic: config.pedantic ?? false,
				generator: (config.generator as any) ?? "ts",
				legacy: config.legacy ?? true,
			},
			runtimeImportPath,
		});

		const schemaVersion = parseSchemaVersion(schemaPath);
		if (schemaVersion !== null) {
			latestVersion = latestVersion === null ? schemaVersion : Math.max(latestVersion, schemaVersion);
		}
	}

	if (latestVersion !== null) {
		await fs.writeFile(
			path.join(resolvedOutput, "latest.ts"),
			createLatestModule(latestVersion),
		);
	}
}

const ASSERT_FUNCTION = `
function assert(condition: boolean, message?: string): asserts condition {
    if (!condition) throw new Error(message ?? "Assertion failed")
}

`;

/**
 * Post-process generated TypeScript to remove Node.js-only imports, optionally
 * rewrite the runtime package import, and expose version metadata for vN schemas.
 */
function postProcessGeneratedTs(
	code: string,
	options: {
		schemaVersion: number | null;
		runtimeImportPath?: string;
	},
): string {
	const { schemaVersion, runtimeImportPath } = options;

	// Remove Node.js assert import
	code = code.replace(/^import assert from "node:assert\/strict"/m, "");
	code = code.replace(/^import assert from "node:assert"/m, "");
	code = code.replace(/^import assert from "assert"/m, "");

	if (runtimeImportPath) {
		code = code.replace(/@bare-ts\/lib/g, runtimeImportPath);
	}

	if (schemaVersion !== null) {
		const configPattern =
			/(const\s+\w+\s*=\s*\/\* @__PURE__ \*\/ bare\.Config\(\{\}\)\n)/;
		if (!configPattern.test(code)) {
			throw new Error("Failed to find bare.Config while injecting SCHEMA_VERSION");
		}

		code = code.replace(
			configPattern,
			`$1\nexport const SCHEMA_VERSION = ${schemaVersion} as const\n`,
		);
	}

	// Inject new assert function
	code += "\n" + ASSERT_FUNCTION;

	return code;
}

function parseSchemaVersion(schemaPath: string): number | null {
	const match = path.basename(schemaPath).match(/^v(\d+)\.bare$/);
	return match ? Number.parseInt(match[1], 10) : null;
}

function createLatestModule(latestVersion: number): string {
	return `// @generated by @vbare/compiler
export * from "./v${latestVersion}";

export const CURRENT_VERSION = ${latestVersion} as const;
`;
}

export { type Config, transform } from "@bare-ts/tools";
